floodwatch/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^forecast/", include("forecast.urls")),
    url(r"^rain/", include("rain.urls")),
]

forecast/urls.py
from django.conf.urls import url
from . import views

app_name = "forecast"

urlpatterns = [
  url(r"^$", views.index, name="index"),
]

rain/urls.py
from django.conf.urls import url
from . import views

app_name = "rain"

urlpatterns = [
  url(r"^$", views.index, name="index"),
  url(r"^(\d+)/$", views.detail, name="detail"),
]

forecast/models.py
from django.db import models

# Create your models here.

rain/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

min_lat = MinValueValidator(-90.0)
max_lat = MaxValueValidator(90.0)
min_lon = MinValueValidator(-180.0)
max_lon = MaxValueValidator(180.0) 


class Gauge(models.Model):
    """
    Represents a rain gauge.
    """
    latitude = models.FloatField(validators=[min_lat, max_lat])
    longitude = models.FloatField(validators=[min_lon, max_lon])
    address = models.CharField(max_length=150)

    def __str__(self):
        return self.address


class Increment(models.Model):
    """
    Represents an increment in recorded rainfall for a gauge.
    """
    gauge = models.ForeignKey(Gauge)
    timestamp = models.DateTimeField()
    amount = models.FloatField()

    class Meta:
        ordering = [ "timestamp" ]

    def __str__(self):
        return "{} [{:.1f}]".format(
          self.timestamp.strftime("%Y-%m-%d:%H:%M"), self.amount)

forecast/views.py
import requests
from datetime import datetime, timedelta
from django.http import Http404
from django.shortcuts import render

API_BASE = "http://environment.data.gov.uk/flood-monitoring/"

def index(request):
    url = API_BASE + "id/3dayforecast"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        issued = data["items"]["issueDatetime"]
        dt = datetime.strptime(issued, "%Y-%m-%dT%H:%M:%S")
        days = [ dt, dt + timedelta(days=1), dt + timedelta(days=2) ]
        context = {
          "summary": data["items"]["forecastSummary"],
          "label": data["items"]["label"],
          "days": days,
        }
        return render(request, "forecast/index.html", context)
    else:
        raise Http404("API call failed")

rain/views.py
import pandas as pd
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Gauge, Increment


def index(request):
    context = {
      "gauges": Gauge.objects.all(),
      "token": settings.MAPBOX_ACCESS_TOKEN
    }
    return render(request, "rain/index.html", context)


def detail(request, id):
    gauge = get_object_or_404(Gauge, pk=id)
    increments = Increment.objects.filter(gauge=gauge)
    timestamps = increments.values_list("timestamp", flat=True)
    rain = increments.values_list("amount", flat=True)

    data = pd.Series(rain, timestamps)
    resampled = data.resample("1H").sum().fillna(0)

    context = {
      "gauge": gauge,
      "time": [ str(t) for t in resampled.index ],
      "rainfall": resampled.values.tolist()
    }
    return render(request, "rain/detail.html", context)

forecast/templates/forecast/index.html
{% extends "base.html" %}
{% block description %}3-day flood forecast{% endblock %}
{% block title %}3-Day Forecast{% endblock %}
{% block content %}
<h1>3-Day Forecast</h1>

<p>{{ summary }}</p>

<div class="row">
  {% for day in days %}
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">{{ day|date:"l j F" }}</div>
      <div class="panel-body text-center">
        <img src="http://environment.data.gov.uk/flood-monitoring/id/3dayforecast/image/{{ forloop.counter }}" alt="Flood forecast map image">
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<p class="text-center">
  ({{ label }})
</p>
{% endblock %}

rain/templates/rain/detail.html
{% extends "base.html" %}
{% block description %}Details for a single rain gauge{% endblock %}
{% block title %}Rain Gauge Details{% endblock %}
{% block head %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}
{% block content %}
<h1>Rain Gauge Details</h1>
<h3>{{ gauge.address }}</h3>
<br>
<p>
Latitude {{ gauge.latitude|floatformat:5 }}&deg;,
Longitude {{ gauge.longitude|floatformat:5 }}&deg;
</p>
<br>
<div id="chart" style="width:600px;height:280px;"></div>
{% endblock %}
{% block scripts %}
<script>
{% autoescape off %}
var data = [{ x: {{ time }}, y: {{ rainfall }} }];
{% endautoescape %}
var layout = {
  margin: { t: 20 },
  yaxis: { title: 'Hourly Total (mm)' }
};
Plotly.plot('chart', data, layout, { scrollZoom: true });
</script>
{% endblock %}

rain/templates/rain/index.html
{% extends "base.html" %}
{% block description %}Rain gauge map{% endblock %}
{% block title %}Rain Gauge Map{% endblock %}
{% block head %}
<script src="https://api.mapbox.com/mapbox.js/v2.3.0/mapbox.js"></script>
<link href="https://api.mapbox.com/mapbox.js/v2.3.0/mapbox.css" rel="stylesheet">
<style>
#map { height:400px; }
</style>
{% endblock %}
{% block content %}
<h1>Rain Gauge Map</h1>
<div id="map"></div>
{% endblock %}
{% block scripts %}
<script>
L.mapbox.accessToken = '{{ token }}';

var map = L.mapbox.map('map', null);

var baseLayers = {
  Streets: L.mapbox.tileLayer('mapbox.streets'),
  Outdoors: L.mapbox.tileLayer('mapbox.outdoors'),
  Satellite: L.mapbox.tileLayer('mapbox.satellite')
};

baseLayers.Streets.addTo(map);
L.control.layers(baseLayers).addTo(map);

var coords = [];
{% for gauge in gauges %}
  var coord = [{{ gauge.latitude }}, {{ gauge.longitude }}];
  var content = '<a href="{% url 'rain:detail' gauge.id %}">{{ gauge.address }}</a><br>Latitude {{ gauge.latitude|floatformat:5 }}&deg;, Longitude {{ gauge.longitude|floatformat:5 }}&deg;';
  L.marker(coord).bindPopup(content, {
    minWidth: 360,
  }).addTo(map);
  coords.push(coord);
{% endfor %}

map.fitBounds(coords);
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head -->
<meta name="description" content="{% block description %}{% endblock %}">
<meta name="author" content="Nick Efford">
<!-- <link rel="icon" href="{% static 'images/favicon.ico' %}"> -->

<title>{% block title %}{% endblock %}</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'css/theme.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
{% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">FloodWatch</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  {% block content %}{% endblock %}
</div><!-- /.container -->

<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>